version:0.2
phases :
  install:
    commands:
    - echo Setting up NODE.js
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt install -y nodejs
  build:
    commands:
    - echo Building....
    - npm build
artifacts:
  files:
    -"**/*"
  discard-paths: no
  base-directory: build
